### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by NohaAlrajhi** [CurtisMJ/tf_keras_shapelets_encoders#1]

**Comment by CurtisMJ** [comment]
I'm sorry but this is not an appropriate way to contact someone about an SO question answered nearly a decade ago. Be careful about posting your email in public as well. If you have questions its best to ask on SO or comment on an existing question. I'm closing this issue as off-topic.

**Comment by NohaAlrajhi** [comment]
I am sorry to bother you but I was so desperate to get a response since I have been stuck for weeks now. Also, could not send you message neither here or there. Could not comment there as well until reaching 50 something there!! 

Anyway, sorry once more for interpreting here. Didn't want to cause you any harm :)
I will be deleting this comment as well.

**Comment by CurtisMJ** [comment]
No worries, good luck :)
